Backend onboarding
CannabisHouseDev/cannabishouse pull request #10
Opened 2021-05-22 05:05 UTC by Shalashtein

Minor changes to the profile table, model routes, locales and views to start building the onboarding page

2021-05-24 10:15 UTC, wolak88 requested changes

2021-05-24 10:15 UTC, wolak88 commented on app/models/profile.rb
> +  validates :pesel, format: { with: /\A(\d{11})\z/ },
Why do we remove translated error message here?

2021-05-24 10:15 UTC, wolak88 commented on app/views/pages/onboarding.html.haml
> +    = profile_form.submit 'Zapisz', class: 'Form-submit'
It's minor but we should stick to translations, but maybe it will be a good task to introduce junior devs

2021-05-24 10:15 UTC, wolak88 commented on app/views/pages/onboarding.html.haml
> +      %h2= "#{pluralize(current_user.profile.errors.count, "error")} prohibited this profile from being saved:"
It's minor but we should stick to translations, but maybe it will be a good task to introduce junior devs

2021-05-24 10:15 UTC, wolak88 commented on config/environments/development.rb
> +  config.active_storage.service = :amazon
I'm not sure about using amazon on dev env instead of `local`

2021-05-24 10:15 UTC, wolak88 commented on config/routes.rb
> +
nit: remove this empty line

2021-05-24 10:15 UTC, wolak88 commented on app/controllers/pages_controller.rb
> +  def roleRouter
`role_router`

2021-05-24 10:15 UTC, wolak88 commented on app/controllers/pages_controller.rb
> +  end
WDYT about creating explicit controllers for those portals and just redirect there using `role_router` if user goes to root path?

I think with this approach we will clutter this controller and it's not a Rails way to do it

2021-05-24 10:15 UTC, wolak88 commented on config/routes.rb
> +    get 'researcher_portal', to: 'pages#researcher', as: 'researcher'
I would remove the `_portal` from those paths

2021-05-24 11:34 UTC, Shalashtein commented on app/models/profile.rb
> +  validates :pesel, format: { with: /\A(\d{11})\z/ },
I18n automaticaly picks up the message from the locales, also I'm moving this validation to `on: :create` on the next push

2021-05-24 11:34 UTC, Shalashtein commented on app/views/pages/onboarding.html.haml
> +    = profile_form.submit 'Zapisz', class: 'Form-submit'
You're right, I forget to switch that when I copied the form, fixing with the next push

2021-05-24 11:34 UTC, Shalashtein commented on app/views/pages/onboarding.html.haml
> +      %h2= "#{pluralize(current_user.profile.errors.count, "error")} prohibited this profile from being saved:"
You're right, I forget to switch that when I copied the form, fixing with the next push

2021-05-24 11:34 UTC, Shalashtein commented on config/environments/development.rb
> +  config.active_storage.service = :amazon
Yes, I was just testing if the aws policy is working, fixing with the next push

2021-05-24 11:35 UTC, Shalashtein commented on app/controllers/pages_controller.rb
> +  end
We can use contraints and lambdas in `config/routes.rb` to redirect users to different controllers based on their role, however it seems like an overkill, because we just want to redirect users to different views, while user specific logic (such as setting free spots in the case of the doctor, or transferring material in the case of the dispensary) would not be in the pages controller but rather in their respective controller. I'll study the option further before mergin

2021-05-25 10:08 UTC, wolak88 approved these changes
LGTM

2021-05-25 10:39 UTC, merged