Doctor fixes
CannabisHouseDev/cannabishouse pull request #110
Opened 2021-07-20 07:29 UTC by Shalashtein

2021-07-20 09:55 UTC, wolak88 requested changes

2021-07-20 09:55 UTC, wolak88 commented on app/javascript/controllers/doctor_controller.js
> +    console.log(id)
nit: remove

2021-07-20 09:55 UTC, wolak88 commented on app/views/doctor_portal/evaluations.html.haml
> +          - if Appointment.find(@selected.id).state == 'done'
It's an antipattern to query db from views.
Please move querying into controller

2021-07-21 09:05 UTC, wolak88 requested changes

2021-07-21 09:05 UTC, wolak88 commented on app/controllers/doctor_portal_controller.rb
> +      @risk = ['green', 'orange', 'red'].index(@selected.participant.profile.risk_calculated)
Are we sure that risk_calculated will be set when we do it for pending appointments?

2021-07-21 09:05 UTC, wolak88 commented on app/controllers/doctor_portal_controller.rb
>      s = Appointment.find(params[:id].to_i)
Let's not use one letter variables which doesn't tell us anything.
Also why do you have to cast parameter here?

2021-07-21 09:09 UTC, roxkon commented on app/controllers/doctor_portal_controller.rb
> +      @risk = ['green', 'orange', 'red'].index(@selected.participant.profile.risk_calculated)
yes, i think it is calculated with algorithm inside our app for the doctor, doctor will have his own option to specify risk

2021-07-21 14:47 UTC, wolak88 approved these changes

2021-07-21 14:50 UTC, merged