add career page and links up social media links
CannabisHouseDev/cannabishouse pull request #111
Opened 2021-07-20 08:55 UTC by MaciejO98

2021-07-20 10:04 UTC, wolak88 requested changes

2021-07-20 10:04 UTC, wolak88 commented on config/locales/en.yml
> +    career: "Carrier"
"Career"

2021-07-21 08:02 UTC, roxkon approved these changes

2021-07-21 11:09 UTC, wolak88 approved these changes

2021-07-21 11:18 UTC, merged