Created class Space (Physical spaces: Offices, Dispensaries...) connected to classes user and address
CannabisHouseDev/cannabishouse pull request #136
Opened 2021-07-26 08:12 UTC by Shalashtein

Also edited the admin dashboard to allow us to create the clinic for the doctor, and added the doctor name and address to the booking page

2021-07-28 10:30 UTC, roxkon reviewed
I found only one thing with admin's password.

2021-07-28 10:30 UTC, roxkon commented on db/seeds.rb
> -password = Rails.application.credentials[Rails.env.to_sym][:admin][:password]
It's important admin password :)

2021-07-28 10:36 UTC, Shalashtein commented on db/seeds.rb
> -password = Rails.application.credentials[Rails.env.to_sym][:admin][:password]
just returned it

2021-07-29 10:29 UTC, wolak88 requested changes

2021-07-29 10:29 UTC, wolak88 commented on app/controllers/spaces_controller.rb
> +        Address.create(@address_params)
Let's use one params here, and create addressable through that

2021-07-29 10:29 UTC, wolak88 commented on app/controllers/spaces_controller.rb
> +      if @space.update(space_params)
Can we update address here?

2021-07-29 10:29 UTC, wolak88 commented on config/routes.rb
> +      patch ':id/order', to: 'admin_portal#update_order', as: 'admin_portal_update_order'
WDYT about going with `order/:id`, I think it's more readable

2021-07-29 21:30 UTC, Shalashtein commented on app/controllers/spaces_controller.rb
> +        Address.create(@address_params)
I wrote this workaround because the form_with isn't naming the nested attributes `address_atributes` instead it's being named `address` and not being permitted, can you help me with why it's not being permitted so I can put them in one param and create the nested address automatically

2021-07-31 09:21 UTC, wolak88 commented on app/controllers/spaces_controller.rb
> +        Address.create(@address_params)
https://guides.rubyonrails.org/form_helpers.html#nested-forms

2021-07-31 13:38 UTC, wolak88 approved these changes

2021-07-31 13:59 UTC, merged