Dispensary flow
CannabisHouseDev/cannabishouse pull request #37
Opened 2021-06-12 13:08 UTC by Shalashtein

- Typo fixed across different files and database
- Data Types fixed on different attributes in database
- Added annotate gem and run rake task
- Added AASM state management gem, and used it to run validation when a transfer of material is initiated

2021-06-13 11:38 UTC, wolak88 requested changes

2021-06-13 11:38 UTC, wolak88 commented on app/models/material.rb
> +  has_many :transfers, class_name: "Transfer", foreign_key: 'receiver_material_id', dependent: :destroy
We can't have two relations with the same name, maybe let's go with `outgoing_transfers` and `incoming_transfers`

2021-06-13 11:38 UTC, wolak88 commented on app/models/material.rb
> +    # Process tranfer if all states transitioned
nit: `transfer`

2021-06-13 11:38 UTC, wolak88 commented on db/seeds.rb
> +Address.destroy_all
Why are we not removing Pages, Posts, Dispensaries?

2021-06-13 11:38 UTC, wolak88 commented on app/models/material.rb
> +  aasm no_direct_assignment: true do
Let's set `whiny_persistence: true` and we will use all transitions with bang `!`

2021-06-13 11:38 UTC, wolak88 commented on app/models/material.rb
> +  end
I'm not sure about this approach, what if one of the intermediate steps fail? 
I think we will have sender_material which is locked and we don't have any way to put it back in ready state.

We can take advantage of some hooks(example code from my project):
```
event Journeys::CommonEventEnum::SUBMIT_FOR_CONSULTATION.to_sym do
          # eCommerce in state, LTDD
          transitions(
            from: Journeys::CommonStatusEnum::QUIZ_PENDING.to_sym,
            to: Journeys::CommonStatusEnum::CONSULTATION_PENDING.to_sym,

            guard: -> { user_completed_quiz?(event: Journeys::CommonEventEnum::SUBMIT_FOR_CONSULTATION.to_sym) }
          )

          # eCommerce out state
          transitions(
            from: Journeys::CommonStatusEnum::QUIZ_PENDING.to_sym,
            to: Journeys::CommonStatusEnum::PRESCRIPTION_TRANSFER_PENDING.to_sym,

            guard: -> { e_commerce_rx_out_of_state?(event: Journeys::CommonEventEnum::SUBMIT_FOR_CONSULTATION.to_sym) },

            after: lambda {
              update!(doctor_products: user_products)
            }
          )

          after lambda {
            update_consultation! unless user.out_of_state?
          }

          after_commit lambda {
            Analytics.track(
              user_id: user.id,
              event: 'ConsultationQuizFinished'
            )
            UserEvent.send(user: user, event: UserEventEnum::QUIZ_FINISHED)

            sync_to_kmg! unless user.out_of_state?
          }
        end
```

2021-06-13 12:35 UTC, Shalashtein commented on db/seeds.rb
> +Address.destroy_all
We aren't using them yet, so far in our app flow and in the seeds we aren't creating Pages or Posts or Dispensaries

2021-06-14 06:27 UTC, Shalashtein commented on app/models/material.rb
> +  has_many :transfers, class_name: "Transfer", foreign_key: 'receiver_material_id', dependent: :destroy
done

2021-06-14 06:27 UTC, Shalashtein commented on app/models/material.rb
> +  aasm no_direct_assignment: true do
done

2021-06-14 06:27 UTC, Shalashtein commented on app/models/material.rb
> +  end
I tried, let's see

2021-06-20 17:34 UTC, wolak88 approved these changes

2021-06-20 17:34 UTC, wolak88 commented on app/models/material.rb
> +    start_tranfer
nit: `transfer`

2021-06-21 20:21 UTC, merged