feature/add responsive layout
CannabisHouseDev/cannabishouse pull request #74
Opened 2021-07-05 20:21 UTC by emeren

2021-07-06 06:27 UTC, wolak88 requested changes

2021-07-06 06:27 UTC, wolak88 commented on config/locales/pl.yml
> +        titleSecondPart: "życie"
We should change it en.yml as well

2021-07-06 06:27 UTC, wolak88 commented on app/views/layouts/_navigation.html.haml
> +    = link_to main_app.root_path, class: '' do
Let's omit empty `class: ''`

2021-07-06 06:27 UTC, wolak88 commented on app/views/layouts/_footer.html.haml
> +            %a.text-gray-600.hover:text-gray-800 Fourth Link
Let's hop on a call to figure out footer links, or just link to `media` and `about` for now and put in company details.
@roxkon WDYT?

2021-07-06 06:29 UTC, wolak88 commented
Also let's merge master as tests are failing

2021-07-06 08:16 UTC, roxkon commented on app/views/layouts/_footer.html.haml
> +            %a.text-gray-600.hover:text-gray-800 Fourth Link
I agree, we can use the view from gromol figma project (https://www.figma.com/file/QmiOLbzLpF1e1GIEd8HCqn/Zeszyt?node-id=302%3A34). We need 2 columns, one with links (about, media) and 2nd with contact informations - i think this would be nice.

2021-07-07 19:17 UTC, Shalashtein approved these changes

2021-07-07 20:27 UTC, CannabisHouseDev reviewed
Very nice, clean and green layout. I'm impressed =D
I've got 2 things:
1. the empty master.key file - propably will cause damage to production
2. sign in modal look very nice, we should do the same with sign up

2021-07-07 20:28 UTC, roxkon commented
I wrote this 2 things.

2021-07-07 21:02 UTC, roxkon approved these changes

2021-07-08 09:16 UTC, wolak88 approved these changes

2021-07-08 09:22 UTC, merged