translations for the participant pages
CannabisHouseDev/cannabishouse pull request #79
Opened 2021-07-07 15:38 UTC by Karol-Maximus

2021-07-08 10:31 UTC, Shalashtein requested changes

2021-07-08 10:31 UTC, Shalashtein commented on app/models/profile.rb
> +  enum gender: %i[kobieta mężczyzna]
These should be localized

2021-07-08 10:31 UTC, Shalashtein commented on app/views/pages/info.haml
> +        = profile_form.text_field :first_name, placeholder: t('models.onboarding.placeholder.first_name'), class: "Form-input rounded bg-gray-200 border-gray-500 #{'border-red-500 bg-red-200' unless
it doesn't hurt, but in the future don't use I18n use t() directly since we're already using the shorthand elsewhere

2021-07-08 10:31 UTC, Shalashtein commented on config/credentials.yml.enc
> +0jr5G2Cp/+tO5VYCZw09XeXhNBAPHFVrWhMToi0utOTUqFwQ2tlMJjq6sJc3qjUyrLOuXvTwG66PrLJk9yfHa/MBPCpHvSgj8j/mRy2gqJoisDcoq+5VVE67E8WFgwhcSQyi5TTWMowsKexPyWylz7DZqSgsF8vG4Ch3TvHTw58G5csLhjwWunt28gw6OIxDDowx+Iq
What did we change in the credentials?

2021-07-08 10:37 UTC, Karol-Maximus commented on app/views/pages/info.haml
> +        = profile_form.text_field :first_name, placeholder: t('models.onboarding.placeholder.first_name'), class: "Form-input rounded bg-gray-200 border-gray-500 #{'border-red-500 bg-red-200' unless
Ok. Should I change it to t() ?

2021-07-08 10:37 UTC, Karol-Maximus commented on config/credentials.yml.enc
> +0jr5G2Cp/+tO5VYCZw09XeXhNBAPHFVrWhMToi0utOTUqFwQ2tlMJjq6sJc3qjUyrLOuXvTwG66PrLJk9yfHa/MBPCpHvSgj8j/mRy2gqJoisDcoq+5VVE67E8WFgwhcSQyi5TTWMowsKexPyWylz7DZqSgsF8vG4Ch3TvHTw58G5csLhjwWunt28gw6OIxDDowx+Iq
@roxkon ?

2021-07-08 10:43 UTC, roxkon commented on config/credentials.yml.enc
> +0jr5G2Cp/+tO5VYCZw09XeXhNBAPHFVrWhMToi0utOTUqFwQ2tlMJjq6sJc3qjUyrLOuXvTwG66PrLJk9yfHa/MBPCpHvSgj8j/mRy2gqJoisDcoq+5VVE67E8WFgwhcSQyi5TTWMowsKexPyWylz7DZqSgsF8vG4Ch3TvHTw58G5csLhjwWunt28gw6OIxDDowx+Iq
this shouldn't be here

2021-07-09 07:58 UTC, Shalashtein commented on app/views/pages/info.haml
> +        = profile_form.text_field :first_name, placeholder: t('models.onboarding.placeholder.first_name'), class: "Form-input rounded bg-gray-200 border-gray-500 #{'border-red-500 bg-red-200' unless
It would be cleaner to fit with the rest, but not mandatory

2021-07-09 09:35 UTC, Karol-Maximus commented on app/views/pages/info.haml
> +        = profile_form.text_field :first_name, placeholder: t('models.onboarding.placeholder.first_name'), class: "Form-input rounded bg-gray-200 border-gray-500 #{'border-red-500 bg-red-200' unless
Ok i've done it on another branch "translation-forms", so this one can be closed now.

2021-07-11 09:12 UTC, Shalashtein commented
Do you want to resolve the conflicts or is everything in the other PR? if everything is in theo ther PR lets close this

2021-07-11 09:12 UTC, closed without merging