translating different small pages
CannabisHouseDev/cannabishouse pull request #98
Opened 2021-07-13 14:11 UTC by Karol-Maximus

2021-07-13 14:19 UTC, wolak88 requested changes
Just some nitpicking

2021-07-13 14:19 UTC, wolak88 commented on config/locales/en.yml
> +        register: "Register"
I think I know what you want to achieve here, but let's add those whitespaces in the view file.

2021-07-13 14:19 UTC, wolak88 commented on config/locales/pl.yml
> +        register: "Zapisz się"
I think I know what you want to achieve here, but let's add those whitespaces in the view file.

2021-07-14 09:07 UTC, roxkon commented on app/views/participant_portal/partials/_questionscol.html.haml
> -        .text-sm.text-gray-600.mb-3.text-center.capitalize.md:text-2xl #{local_assigns[:s].survey.study.title}
I think that Study Title should be capitalized

2021-07-14 09:07 UTC, roxkon commented on config/locales/pl.yml
>          dry_30: "Susz: 20g miesięcznie, Olejek: 10g miesięcznie"
Is it right or is it wrong? I think dry_30 should be "Susz: 30g miesięcznie, Olejki: 15g miesięcznie"

2021-07-14 09:19 UTC, Karol-Maximus commented on config/locales/pl.yml
>          dry_30: "Susz: 20g miesięcznie, Olejek: 10g miesięcznie"
Nope. it is changed now.

2021-07-14 09:20 UTC, Karol-Maximus commented on app/views/participant_portal/partials/_questionscol.html.haml
> -        .text-sm.text-gray-600.mb-3.text-center.capitalize.md:text-2xl #{local_assigns[:s].survey.study.title}
It is a survey title that's why i removed the capitalizing

2021-07-14 09:20 UTC, Karol-Maximus commented on config/locales/pl.yml
> +        register: "Zapisz się"
done

2021-07-14 09:20 UTC, Karol-Maximus commented on config/locales/en.yml
> +        register: "Register"
done

2021-07-14 10:46 UTC, wolak88 approved these changes

2021-07-14 15:12 UTC, merged