admin_orders_partial
CannabisHouseDev/cannabishouse pull request #99
Opened 2021-07-13 17:54 UTC by MaciejO98

2021-07-13 18:36 UTC, Shalashtein requested changes

2021-07-13 18:36 UTC, Shalashtein commented on app/models/material.rb
> +    return unless self.owner.profile.dispensary?
There's no method called `dispensary?` use `.role != 'dispensary` instead

2021-07-13 18:36 UTC, Shalashtein commented on app/models/material.rb
> +    warehouse_material = Material.includes(owner: :profile).includes(:material_type).where(owner: {profiles: {role: :warehouse}}, material_type: {id: self.material_type_id}).first
Multiple Material instances might have the same type, perhaps if we just include the id of the material that's lo on stock somewhere

2021-07-14 10:33 UTC, wolak88 commented on app/models/material.rb
> +    return unless self.owner.profile.dispensary?
@Shalashtein 
In rails creating an enum creates scope on model, so you can do `Profile.dispensary` and you will get only profiles that are dispensaries also you get `dispensary?` and some other methods

2021-07-14 10:39 UTC, wolak88 commented on app/models/material.rb
> +    warehouse_material = Material.includes(owner: :profile).includes(:material_type).where(owner: {profiles: {role: :warehouse}}, material_type: {id: self.material_type_id}).first
Yeah, I think we should create `MaterialRequest` class where we will store material type, amount and user(dispensary) which is making the request. I don't know if it should be connected to particular warehouse or shouldn't

2021-07-18 11:37 UTC, Shalashtein approved these changes

2021-07-18 11:37 UTC, merged